/// @description  playFieldSetup
/// @function  playFieldSetup
/// @param  StartX
/// @param  StartY
/// @param  Width
/// @param  Height
global.playAreaStartX = argument0
global.playAreaStartY = argument1
global.playAreaWidth = argument2
global.playAreaHeight = argument3